services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: "chats-bot"

    volumes:
      - ..:/app/

    env_file:
      - ../.env

    ports:
      - "5679:5678"

    command: "python setup.py"
