services:
  bot_consumer:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: "bot-faststream"

    ports:
      - "5677:5678"

    volumes:
      - ..:/app/

    env_file:
      - ../.env

    command: "debugpy --listen 5678 -m faststream run --factory core.consumers.main:get_app --reload"
